autocmd BufNewFile *.py,*.cc,*.sh,*.java exec ":call SetTitle()"

func SetTitle()  
    if expand("%:e") == 'sh'  
        call setline(1,"#!/bin/bash")
        call setline(2, "#")  
        call setline(3, "#  ")
        call setline(4, "# Created By OceanHo(gzhehai@foxmail.com) AT ".strftime("%F"))
        call setline(5, "#")
        call cursor(3,3)
    endif
endfunc

set tabstop=3
set expandtab
set autoindent
